# Generated by Django 4.2.7 on 2026-06-03 06:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Activated after payment')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='landlords/photos/')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('single', 'Single Room'), ('1bedroom', '1 Bedroom'), ('2bedroom', '2 Bedroom'), ('3bedroom', '3 Bedroom'), ('4bedroom', '4+ Bedroom'), ('studio', 'Studio'), ('bungalow', 'Bungalow')], max_length=20)),
                ('price', models.PositiveIntegerField(help_text='Monthly rent in KSh')),
                ('location', models.CharField(help_text='Estate / area in Nakuru', max_length=200)),
                ('address', models.TextField(help_text='Full address details')),
                ('directions', models.TextField(help_text='Directions to reach the property')),
                ('description', models.TextField()),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated: Water, Electricity, WiFi...')),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=15)),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approves before going live')),
                ('is_available', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='landlords.landlord')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('is_main', models.BooleanField(default=False, help_text='Main cover photo')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='landlords.property')),
            ],
            options={
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
    ]
