# Generated by Django 4.2.7 on 2026-06-03 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('landlord', 'Landlord Registration'), ('tenant', 'Tenant Subscription')], max_length=20)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.CharField(blank=True, max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('mpesa_code', models.CharField(blank=True, help_text='M-Pesa transaction code', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_till_number', models.CharField(default='', help_text='Your M-Pesa Till Number', max_length=20)),
                ('landlord_fee', models.PositiveIntegerField(default=300, help_text='One-time fee for landlords (KSh)')),
                ('tenant_fee', models.PositiveIntegerField(default=100, help_text='One-time fee for tenants (KSh)')),
                ('site_name', models.CharField(default='Find Your Home Kenya', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
